Repository IlyaM1/TestBuilder, pull requests merged in 2022-08, with the labels that each got.

#33 Authorization and registration func
  auth_reg.py
  authorization.py
  db/convert.py
  db/hash.py
  db/sqlite.py
  main.py
Labels: enhancement, back-end

#36 backend and frontend communication in authorization is implemented
  .gitignore
  Interface/Authorization.py
  auth_reg.py
  db/sqlite.py
  main.py
Labels: front-end, back-end

#55 Made basic comments for all front-end classes
  Custom_Widgets/CollapsibleBox.py
  Custom_Widgets/Item.py
  Custom_Widgets/LineEdit_with_explanation.py
  Interface/Admin_test_view.py
  Interface/Admin_user_view.py
  Interface/Admin_view_tests_and_users.py
  Interface/Authorization.py
  Interface/Ending_test_widget.py
  Interface/Solving_test_widget.py
  Interface/View_all_tests.py
Labels: documentation

#56 Issue #45
  Interface/Admin_test_view.py
  Interface/Admin_user_view.py
  Interface/Admin_view_tests_and_users.py
  Interface/Authorization.py
  config.py
  db/sqlite.py
  db/user.py
  main.py
Labels: enhancement, back-end

#57 Issue#54
  Custom_Widgets/LineEdit_with_explanation.py
  Interface/Admin_test_view.py
  Interface/Admin_user_view.py
Labels: front-end

#60 Issue #37
  Interface/Authorization.py
  db/sqlite.py
Labels: back-end

#61 Remake admin test view
  Custom_Widgets/Button_with_information.py
  Custom_Widgets/Deletable_LineEdit_with_explanation.py
  Custom_Widgets/Deletable_TextInput.py
  Custom_Widgets/LineEdit_with_explanation.py
  Custom_Widgets/Question_widget_with_array_of_labels.py
  Interface/Admin_test_view.py
  Interface/Trash_Bin.png
  Interface/css/Admin_test_view.css
  Interface/red_cross_delete.png
  config.py
  main.py
Labels: front-end

#62 Splitted Item in two Widgets
  Custom_Widgets/Clickable_label.py
  Custom_Widgets/Clickable_label_with_delete_buttons.py
  Interface/Admin_view_tests_and_users.py
  Interface/View_all_tests.py
Labels: front-end

#64 Save answers from inputs in Solving_test_widget
  Interface/Solving_test_widget.py
Labels: front-end

#66 Finishing test
  Interface/Solving_test_widget.py
Labels: front-end

#68 Buttons in Admin_view_tests_and_users
  Custom_Widgets/Clickable_label_with_delete_buttons.py
  Interface/Admin_view_tests_and_users.py
  Interface/css/Admin_view_tests_and_users.css
  Interface/edit_icon.png
  Interface/see_icon.png
Labels: front-end

#69 Beautiful authorization window
  Interface/Authorization.py
  Interface/authorization.png
  Interface/css/Authorization.css
  config.py
  main.py
Labels: front-end

#72 Connected all Admin widgets
  Custom_Widgets/Clickable_label_with_delete_buttons.py
  Interface/Admin_test_view.py
  Interface/Admin_user_view.py
  Interface/Admin_view_tests_and_users.py
  Interface/Authorization.py
  Interface/Ending_test_widget.py
  Interface/Solving_test_widget.py
  Interface/View_all_tests.py
  config.py
  main.py
Labels: front-end

#74 end of work on #51
  Interface/Ending_test_widget.py
  Interface/Solving_test_widget.py
  auth_reg.py
  db/hash.py
  db/sqlite.py
  db/user.py
  main.py
Labels: back-end

#77 Connected all widgets
  Custom_Widgets/Clickable_label.py
  Custom_Widgets/Clickable_label_with_delete_buttons.py
  Interface/Authorization.py
  Interface/Ending_test_widget.py
  Interface/Solving_test_widget.py
  Interface/View_all_tests.py
  main.py
Labels: front-end

#78 Fixed expanding of CollapsibleBox
  Custom_Widgets/CollapsibleBox.py
Labels: bug, front-end
