Repository IlyaM1/TestBuilder, pull requests merged in 2023-01, with the labels that each got.

#84 Refactor admin test view
  Interface/Admin_test_view.py
Labels: front-end

#85 Redesign of Ending_test_widget
  Interface/Ending_test_widget.py
  Interface/css/Ending_test_widget.css
Labels: front-end

#87 some fixes on auth and testing systems
  Interface/Solving_test_widget.py
  db/sqlite.py
Labels: back-end

#88 Made saving test in self.test after pressing "Save" button
  Interface/Admin_test_view.py
Labels: bug, front-end

#91 Issue#89
  Custom_Widgets/Clickable_label_with_delete_buttons.py
  Interface/Admin_user_view.py
  Interface/Admin_view_tests_and_users.py
Labels: front-end

#93 Made generate_word_ending function
  Interface/Admin_view_tests_and_users.py
  Interface/View_all_tests.py
Labels: front-end
